import FloatingDockDemo from "@/app/components/Navbar";
import AssistiveTouch from "@/app/components/AssistiveTouch";
import { BackgroundBeams } from '@/app/components/ui/background-beams';

import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Harshan | Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased relative">
        <div className="fixed inset-0 -z-50 pointer-events-none">
          <BackgroundBeams />
        </div>

        {/* Mobile Navigation */}
        <AssistiveTouch />

        <main className="relative z-10 pt-10">
          {children}
        </main>

        <div className="fixed bottom-0 left-0 w-full z-50 pb-safe hidden md:block">
          <FloatingDockDemo />
        </div>
      </body>
    </html>
  );
}
